services:

  sonos-server:
    build: .
    container_name: my-sonos-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./media_assets:/app/media_assets:ro
      - ./tokens.json:/app/tokens.json
    env_file:
      - .env.cloud
    environment:
      - MEDIA_DIR=/app/media_assets
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080

  ngrok:
    image: ngrok/ngrok:latest
    container_name: sonos-ngrok
    restart: unless-stopped
    command: http localhost:8080 --domain=${NGROK_DOMAIN} --log=stdout
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    network_mode: host
